/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdminRouteImport } from './routes/app._admin'
import { Route as AppCasesRouteImport } from './routes/app.cases'
import { Route as AppGovernanceRouteImport } from './routes/app.governance'
import { Route as AppQueueRouteImport } from './routes/app.queue'
import { Route as AppReferencesRouteImport } from './routes/app.references'
import { Route as AppReviewRouteImport } from './routes/app.review'
import { Route as AppAdminRulesRouteImport } from './routes/app._admin.rules'
import { Route as AppAdminSetupRouteImport } from './routes/app._admin.setup'
import { Route as AppCaseCaseIdRouteImport } from './routes/app.case.$caseId'
import { Route as AppProductsIndexRouteImport } from './routes/app.products.index'
import { Route as AppProductsHogCodeRouteImport } from './routes/app.products.$hogCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppGovernanceRoute = AppGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppReferencesRoute = AppReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRulesRoute = AppAdminRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSetupRoute = AppAdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppCaseCaseIdRoute = AppCaseCaseIdRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsHogCodeRoute = AppProductsHogCodeRouteImport.update({
  id: '/products/$hogCode',
  path: '/products/$hogCode',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/cases': typeof AppCasesRoute
  '/app/governance': typeof AppGovernanceRoute
  '/app/queue': typeof AppQueueRoute
  '/app/references': typeof AppReferencesRoute
  '/app/review': typeof AppReviewRoute
  '/app/': typeof AppIndexRoute
  '/app/rules': typeof AppAdminRulesRoute
  '/app/setup': typeof AppAdminSetupRoute
  '/app/case/$caseId': typeof AppCaseCaseIdRoute
  '/app/products/$hogCode': typeof AppProductsHogCodeRoute
  '/app/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AppIndexRoute
  '/app/cases': typeof AppCasesRoute
  '/app/governance': typeof AppGovernanceRoute
  '/app/queue': typeof AppQueueRoute
  '/app/references': typeof AppReferencesRoute
  '/app/review': typeof AppReviewRoute
  '/app/rules': typeof AppAdminRulesRoute
  '/app/setup': typeof AppAdminSetupRoute
  '/app/case/$caseId': typeof AppCaseCaseIdRoute
  '/app/products/$hogCode': typeof AppProductsHogCodeRoute
  '/app/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/_admin': typeof AppAdminRouteWithChildren
  '/app/cases': typeof AppCasesRoute
  '/app/governance': typeof AppGovernanceRoute
  '/app/queue': typeof AppQueueRoute
  '/app/references': typeof AppReferencesRoute
  '/app/review': typeof AppReviewRoute
  '/app/': typeof AppIndexRoute
  '/app/_admin/rules': typeof AppAdminRulesRoute
  '/app/_admin/setup': typeof AppAdminSetupRoute
  '/app/case/$caseId': typeof AppCaseCaseIdRoute
  '/app/products/$hogCode': typeof AppProductsHogCodeRoute
  '/app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/cases'
    | '/app/governance'
    | '/app/queue'
    | '/app/references'
    | '/app/review'
    | '/app/'
    | '/app/rules'
    | '/app/setup'
    | '/app/case/$caseId'
    | '/app/products/$hogCode'
    | '/app/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/app/cases'
    | '/app/governance'
    | '/app/queue'
    | '/app/references'
    | '/app/review'
    | '/app/rules'
    | '/app/setup'
    | '/app/case/$caseId'
    | '/app/products/$hogCode'
    | '/app/products'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/_admin'
    | '/app/cases'
    | '/app/governance'
    | '/app/queue'
    | '/app/references'
    | '/app/review'
    | '/app/'
    | '/app/_admin/rules'
    | '/app/_admin/setup'
    | '/app/case/$caseId'
    | '/app/products/$hogCode'
    | '/app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_admin': {
      id: '/app/_admin'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cases': {
      id: '/app/cases'
      path: '/cases'
      fullPath: '/app/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/governance': {
      id: '/app/governance'
      path: '/governance'
      fullPath: '/app/governance'
      preLoaderRoute: typeof AppGovernanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queue': {
      id: '/app/queue'
      path: '/queue'
      fullPath: '/app/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/references': {
      id: '/app/references'
      path: '/references'
      fullPath: '/app/references'
      preLoaderRoute: typeof AppReferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_admin/rules': {
      id: '/app/_admin/rules'
      path: '/rules'
      fullPath: '/app/rules'
      preLoaderRoute: typeof AppAdminRulesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/_admin/setup': {
      id: '/app/_admin/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppAdminSetupRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/case/$caseId': {
      id: '/app/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/app/case/$caseId'
      preLoaderRoute: typeof AppCaseCaseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/products'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/$hogCode': {
      id: '/app/products/$hogCode'
      path: '/products/$hogCode'
      fullPath: '/app/products/$hogCode'
      preLoaderRoute: typeof AppProductsHogCodeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminRulesRoute: typeof AppAdminRulesRoute
  AppAdminSetupRoute: typeof AppAdminSetupRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminRulesRoute: AppAdminRulesRoute,
  AppAdminSetupRoute: AppAdminSetupRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCasesRoute: typeof AppCasesRoute
  AppGovernanceRoute: typeof AppGovernanceRoute
  AppQueueRoute: typeof AppQueueRoute
  AppReferencesRoute: typeof AppReferencesRoute
  AppReviewRoute: typeof AppReviewRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCaseCaseIdRoute: typeof AppCaseCaseIdRoute
  AppProductsHogCodeRoute: typeof AppProductsHogCodeRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCasesRoute: AppCasesRoute,
  AppGovernanceRoute: AppGovernanceRoute,
  AppQueueRoute: AppQueueRoute,
  AppReferencesRoute: AppReferencesRoute,
  AppReviewRoute: AppReviewRoute,
  AppIndexRoute: AppIndexRoute,
  AppCaseCaseIdRoute: AppCaseCaseIdRoute,
  AppProductsHogCodeRoute: AppProductsHogCodeRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
