/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppReviewRouteImport } from './routes/app.review'
import { Route as AppQueueRouteImport } from './routes/app.queue'
import { Route as AppCasesRouteImport } from './routes/app.cases'
import { Route as AppCaseCaseIdRouteImport } from './routes/app.case.$caseId'
import { Route as AppAdminSetupRouteImport } from './routes/app._admin.setup'
import { Route as AppAdminRulesRouteImport } from './routes/app._admin.rules'
import { Route as AppAdminReferencesRouteImport } from './routes/app._admin.references'
import { Route as AppAdminProductsRouteImport } from './routes/app._admin.products'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppCaseCaseIdRoute = AppCaseCaseIdRouteImport.update({
  id: '/case/$caseId',
  path: '/case/$caseId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSetupRoute = AppAdminSetupRouteImport.update({
  id: '/_admin/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRulesRoute = AppAdminRulesRouteImport.update({
  id: '/_admin/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReferencesRoute = AppAdminReferencesRouteImport.update({
  id: '/_admin/references',
  path: '/references',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminProductsRoute = AppAdminProductsRouteImport.update({
  id: '/_admin/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/cases': typeof AppCasesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/review': typeof AppReviewRoute
  '/app/': typeof AppIndexRoute
  '/app/products': typeof AppAdminProductsRoute
  '/app/references': typeof AppAdminReferencesRoute
  '/app/rules': typeof AppAdminRulesRoute
  '/app/setup': typeof AppAdminSetupRoute
  '/app/case/$caseId': typeof AppCaseCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/cases': typeof AppCasesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/review': typeof AppReviewRoute
  '/app': typeof AppIndexRoute
  '/app/products': typeof AppAdminProductsRoute
  '/app/references': typeof AppAdminReferencesRoute
  '/app/rules': typeof AppAdminRulesRoute
  '/app/setup': typeof AppAdminSetupRoute
  '/app/case/$caseId': typeof AppCaseCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/cases': typeof AppCasesRoute
  '/app/queue': typeof AppQueueRoute
  '/app/review': typeof AppReviewRoute
  '/app/': typeof AppIndexRoute
  '/app/_admin/products': typeof AppAdminProductsRoute
  '/app/_admin/references': typeof AppAdminReferencesRoute
  '/app/_admin/rules': typeof AppAdminRulesRoute
  '/app/_admin/setup': typeof AppAdminSetupRoute
  '/app/case/$caseId': typeof AppCaseCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/cases'
    | '/app/queue'
    | '/app/review'
    | '/app/'
    | '/app/products'
    | '/app/references'
    | '/app/rules'
    | '/app/setup'
    | '/app/case/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/cases'
    | '/app/queue'
    | '/app/review'
    | '/app'
    | '/app/products'
    | '/app/references'
    | '/app/rules'
    | '/app/setup'
    | '/app/case/$caseId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/cases'
    | '/app/queue'
    | '/app/review'
    | '/app/'
    | '/app/_admin/products'
    | '/app/_admin/references'
    | '/app/_admin/rules'
    | '/app/_admin/setup'
    | '/app/case/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queue': {
      id: '/app/queue'
      path: '/queue'
      fullPath: '/app/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cases': {
      id: '/app/cases'
      path: '/cases'
      fullPath: '/app/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/case/$caseId': {
      id: '/app/case/$caseId'
      path: '/case/$caseId'
      fullPath: '/app/case/$caseId'
      preLoaderRoute: typeof AppCaseCaseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_admin/setup': {
      id: '/app/_admin/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppAdminSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_admin/rules': {
      id: '/app/_admin/rules'
      path: '/rules'
      fullPath: '/app/rules'
      preLoaderRoute: typeof AppAdminRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_admin/references': {
      id: '/app/_admin/references'
      path: '/references'
      fullPath: '/app/references'
      preLoaderRoute: typeof AppAdminReferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_admin/products': {
      id: '/app/_admin/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppAdminProductsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCasesRoute: typeof AppCasesRoute
  AppQueueRoute: typeof AppQueueRoute
  AppReviewRoute: typeof AppReviewRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminProductsRoute: typeof AppAdminProductsRoute
  AppAdminReferencesRoute: typeof AppAdminReferencesRoute
  AppAdminRulesRoute: typeof AppAdminRulesRoute
  AppAdminSetupRoute: typeof AppAdminSetupRoute
  AppCaseCaseIdRoute: typeof AppCaseCaseIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCasesRoute: AppCasesRoute,
  AppQueueRoute: AppQueueRoute,
  AppReviewRoute: AppReviewRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminProductsRoute: AppAdminProductsRoute,
  AppAdminReferencesRoute: AppAdminReferencesRoute,
  AppAdminRulesRoute: AppAdminRulesRoute,
  AppAdminSetupRoute: AppAdminSetupRoute,
  AppCaseCaseIdRoute: AppCaseCaseIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
